version: "3.2"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwe123
      MONGO_INITDB_DATABASE: capytcha
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: admin
    volumes:
      - ./container/scripts:/docker-entrypoint-initdb.d
    command: --auth

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwe123

  app:
    container_name: capytcha
    build: .
    depends_on:
      - mongo
      - mongo-express
    environment:
      JWT_SECRET: "super_tropper_secret"
      JWT_ALGORITHM: "HS256"
      IMAGE_STORAGE: "LOCAL" # or S3
      IMAGE_STORAGE_PATH: "./static"
      MONGODB_URI: "mongodb://admin:admin@mongo:27017/capytcha"
      APP_NAME: "capytcha"
    volumes:
      - ./:/app
      - /app/.env
    ports:
      - "8080:8080"
    command: dev
